name: Lint and Format with Ruff

on: [push]

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff

      - name: Apply lint findings with Ruff
        run: ruff check --fix --target-version=py39

      - name: Format code with Ruff
        run: ruff format

      - name: Push changes back to the repository, if any.
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Apply Ruff lint and format fixes"
            git push
          else
            echo "No changes to push."
